---
title: "Synthetic lethal paralog expression vs. drug sensitivity"
author: "Phoebe Parrish"
date: "2023-09-20"
output: html_document
---

# Setup

```{r setup, include=FALSE}

library(tidyverse)
library(ggrepel)
library(ggforce)
library(ggsignif)
library(RColorBrewer)
library(ggpubr) # another way to do significance bars
library(ggprism) # another significance bar package...
library(scales) # scientific notation
library(ggtext) # for using superscript in labels
library(DescTools) # for robust scaling
library(kableExtra)
library(ggrastr)

```


### Assign variables
```{r}

date <- Sys.Date()

in_dir <- file.path("..", "results/integrated_dfs")

out_dir <- file.path("..", "results/expression_output")

options(dplyr.summarise.inform = FALSE)

```


### Import files

```{r, message = FALSE}

d.DeKegel_top5_pairs_drug_sens_expr_annot <- read_rds(file.path(in_dir, "d.DeKegel_top5_pairs_drug_sens_expr_annot"))

```

#### Reformat DFs
```{r}

## keep only relevant columns
d.DeKegel_top5_pairs_drug_sens_expr <- d.DeKegel_top5_pairs_drug_sens_expr_annot %>%
  dplyr::select(-c(entrez_pair:prediction_rank, prediction_score:family_size,
                   broad_id, primary_disease, subtype_disease))

## how many gene pairs are included in the paralog dataset?
d.DeKegel_top5_pairs_drug_sens_expr %>%
  distinct(sorted_gene_pair) %>%
  nrow()

```

### Import functions

```{r}

source("shared_functions.R")

```


# Paralog analysis

## PRISM Phase 1 drug sensitivity

```{r}

## add target col so single-gene functions will work
d.DeKegel_top5_pairs_drug_sens_expr <- d.DeKegel_top5_pairs_drug_sens_expr %>%
  mutate(target = sorted_gene_pair)

```

### Continuous/linear regression

```{r}

## A1 expr

## use broom::glance to get rsquared and pval
d.DeKegel_top5_pairs_drug_sens_A1_expr_lm_summary <- d.DeKegel_top5_pairs_drug_sens_expr %>%
  filter(!is.na(dependency)) %>%
  filter(!is.na(A1_log_tpm)) %>%
  group_by(target, compound_id) %>%
  group_modify(~ broom::glance(lm(dependency ~ A1_log_tpm, data = .x))) %>%
  dplyr::ungroup() %>%
  rename(r_squared = r.squared, p_val = p.value)

## FDR-adjust p-vals for multiple testing and add back to summary DF
d.stats <- BH_adjust(d.DeKegel_top5_pairs_drug_sens_A1_expr_lm_summary)

d.DeKegel_top5_pairs_drug_sens_A1_expr_lm_summary <- d.stats %>%
  dplyr::select(-p_val) %>%
  right_join(d.DeKegel_top5_pairs_drug_sens_A1_expr_lm_summary, by = c("target", "compound_id")) %>%
  dplyr::select(target, compound_id, r_squared, p_val, fdr)

## use broom::tidy to get slope
## note: group_modify expects a DF output
d.DeKegel_top5_pairs_drug_sens_A1_expr_lm_slope <- d.DeKegel_top5_pairs_drug_sens_expr %>%
  filter(!is.na(dependency)) %>%
  filter(!is.na(A1_log_tpm)) %>%
  group_by(target, compound_id) %>%
  group_modify(~ broom::tidy(lm(dependency ~ A1_log_tpm, data = .x))) %>%
  dplyr::ungroup() %>%
  ## extract slope of lm fit line from output
  filter(term == "A1_log_tpm") %>%
  rename(slope = estimate) %>%
  dplyr::select(target, compound_id, slope) 

## add rsquared, p-val, fdr, and slope info to main DF
d.DeKegel_top5_pairs_drug_sens_A1_expr_lm <- d.DeKegel_top5_pairs_drug_sens_expr %>%
  left_join(d.DeKegel_top5_pairs_drug_sens_A1_expr_lm_summary, by = c("target", "compound_id")) %>%
  left_join(d.DeKegel_top5_pairs_drug_sens_A1_expr_lm_slope, by = c("target", "compound_id")) %>%
  filter(!is.na(dependency)) %>%
  filter(!is.na(A1_log_tpm))

summarize_stats(d.DeKegel_top5_pairs_drug_sens_A1_expr_lm)

```

```{r}

## A2 expr

## use broom::glance to get rsquared and pval
d.DeKegel_top5_pairs_drug_sens_A2_expr_lm_summary <- d.DeKegel_top5_pairs_drug_sens_expr %>%
  filter(!is.na(dependency)) %>%
  filter(!is.na(A2_log_tpm)) %>%
  group_by(target, compound_id) %>%
  group_modify(~ broom::glance(lm(dependency ~ A2_log_tpm, data = .x))) %>%
  dplyr::ungroup() %>%
  rename(r_squared = r.squared, p_val = p.value)

## FDR-adjust p-vals for multiple testing and add back to summary DF
d.stats <- BH_adjust(d.DeKegel_top5_pairs_drug_sens_A2_expr_lm_summary)

d.DeKegel_top5_pairs_drug_sens_A2_expr_lm_summary <- d.stats %>%
  dplyr::select(-p_val) %>%
  right_join(d.DeKegel_top5_pairs_drug_sens_A2_expr_lm_summary, by = c("target", "compound_id")) %>%
  dplyr::select(target, compound_id, r_squared, p_val, fdr)

## use broom::tidy to get slope
## note: group_modify expects a DF output
d.DeKegel_top5_pairs_drug_sens_A2_expr_lm_slope <- d.DeKegel_top5_pairs_drug_sens_expr %>%
  filter(!is.na(dependency)) %>%
  filter(!is.na(A2_log_tpm)) %>%
  group_by(target, compound_id) %>%
  group_modify(~ broom::tidy(lm(dependency ~ A2_log_tpm, data = .x))) %>%
  dplyr::ungroup() %>%
  ## extract slope of lm fit line from output
  filter(term == "A2_log_tpm") %>%
  rename(slope = estimate) %>%
  dplyr::select(target, compound_id, slope) 

## add rsquared, p-val, fdr, and slope info to main DF
d.DeKegel_top5_pairs_drug_sens_A2_expr_lm <- d.DeKegel_top5_pairs_drug_sens_expr %>%
  left_join(d.DeKegel_top5_pairs_drug_sens_A2_expr_lm_summary, by = c("target", "compound_id")) %>%
  left_join(d.DeKegel_top5_pairs_drug_sens_A2_expr_lm_slope, by = c("target", "compound_id")) %>%
  filter(!is.na(dependency)) %>%
  filter(!is.na(A2_log_tpm))

summarize_stats(d.DeKegel_top5_pairs_drug_sens_A2_expr_lm)

```


```{r}

d.DeKegel_top5_pairs_drug_sens_A1_expr_lm %>%
  distinct(target, compound_id, .keep_all = TRUE) %>%
  mutate(slope_flag = ifelse(slope < 0, "negative", "positive")) %>%
  group_by(slope_flag) %>%
  summarize(n = n()) %>%
  print_kbl()

d.DeKegel_top5_pairs_drug_sens_A2_expr_lm %>%
  distinct(target, compound_id, .keep_all = TRUE) %>%
  mutate(slope_flag = ifelse(slope < 0, "negative", "positive")) %>%
  group_by(slope_flag) %>%
  summarize(n = n()) %>%
  print_kbl()

```


```{r}

## get low expression = low LFC pairs (positive slope)
d.DeKegel_top5_pairs_drug_sens_A1_expr_lm_pos_slope <-d.DeKegel_top5_pairs_drug_sens_A1_expr_lm %>%
  filter(slope > 0)
summarize_stats(d.DeKegel_top5_pairs_drug_sens_A1_expr_lm_pos_slope)

## get high expression = low LFC pairs (negative slope)
d.DeKegel_top5_pairs_drug_sens_A1_expr_lm_neg_slope <- d.DeKegel_top5_pairs_drug_sens_A1_expr_lm %>%
  filter(slope < 0)
summarize_stats(d.DeKegel_top5_pairs_drug_sens_A1_expr_lm_neg_slope)

## get low expression = low LFC pairs (positive slope)
d.DeKegel_top5_pairs_drug_sens_A2_expr_lm_pos_slope <-d.DeKegel_top5_pairs_drug_sens_A2_expr_lm %>%
  filter(slope > 0)
summarize_stats(d.DeKegel_top5_pairs_drug_sens_A2_expr_lm_pos_slope)

## get high expression = low LFC pairs (negative slope)
d.DeKegel_top5_pairs_drug_sens_A2_expr_lm_neg_slope <- d.DeKegel_top5_pairs_drug_sens_A2_expr_lm %>%
  filter(slope < 0)
summarize_stats(d.DeKegel_top5_pairs_drug_sens_A2_expr_lm_neg_slope)

```

#### Plot A1 top hits

```{r}

A1_top_hits <- d.DeKegel_top5_pairs_drug_sens_A1_expr_lm_pos_slope %>%
  dplyr::select(target, compound_name, r_squared, fdr) %>%
  distinct(target, compound_name, .keep_all = TRUE) %>%
  arrange(fdr) 

print_kbl(head(A1_top_hits, n = 20))

```


```{r, message = FALSE, fig.height = 8}

A1_top_hits_plot_list <- A1_top_hits %>%
  arrange(fdr) %>%
  unite("target_compound_label", c("target", "compound_name"), sep = "\n", remove = FALSE) %>%
  head(n = 9) %>%
  pull(target_compound_label)

make_lm_plot(d.DeKegel_top5_pairs_drug_sens_A1_expr_lm_pos_slope, A1_top_hits_plot_list, A1_log_tpm)

```

#### Plot A2 top hits

```{r}

A2_top_hits <- d.DeKegel_top5_pairs_drug_sens_A2_expr_lm_pos_slope %>%
  dplyr::select(target, compound_name, r_squared, fdr) %>%
  distinct(target, compound_name, .keep_all = TRUE) %>%
  arrange(fdr) 

print_kbl(head(A2_top_hits, n = 20))

```


```{r, message = FALSE, fig.height = 8}

A2_top_hits_plot_list <- A2_top_hits %>%
  arrange(fdr) %>%
  unite("target_compound_label", c("target", "compound_name"), sep = "\n", remove = FALSE) %>%
  head(n = 9) %>%
  pull(target_compound_label)

make_lm_plot(d.DeKegel_top5_pairs_drug_sens_A2_expr_lm_pos_slope, A2_top_hits_plot_list, A2_log_tpm)

```


### Outliers for top lm hits

```{r}

## A2 top hits
target_list <- c("AKT1_AKT2", "AKT2_AKT3", "AKT1_AKT3", "PTPN11_PTPN6", "CDK2_CDK5", "CDK1_CDK2", "MAP2K1_MAP2K2")
compound_list <- c("GSK2110183", "MK−2206", "GDC−0068", "AZD5363", "BVT_948", "bosutinib", "NU6027", "canertinib")

## robustly scale expression data
d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_unfiltered <- d.DeKegel_top5_pairs_drug_sens_expr %>%
  filter(target %in% target_list) %>%
  filter(grepl(str_c(compound_list, collapse = "|"), compound_name)) %>%
  filter(!is.na(A2_log_tpm) | !is.na(dependency)) %>%
  group_by(target, compound_id) %>%
  mutate(scaled_A2_log_tpm = RobScale(A2_log_tpm, center = TRUE, scale = TRUE)) %>%
  mutate(A2_expr_outlier_flag = case_when(
    scaled_A2_log_tpm < -1.5 ~ "low",
    scaled_A2_log_tpm > 1.5 ~ "high",
    TRUE ~ "neither")) %>%
  mutate(scaled_A1_log_tpm = RobScale(A1_log_tpm, center = TRUE, scale = TRUE)) %>%
  mutate(A1_expr_outlier_flag = case_when(
    scaled_A1_log_tpm < -1.5 ~ "low",
    scaled_A1_log_tpm > 1.5 ~ "high",
    TRUE ~ "neither")) %>%
  ungroup() %>%
  mutate(A2_expr_outlier_flag = factor(A2_expr_outlier_flag, levels = c("low", "neither", "high")))%>%
  mutate(A1_expr_outlier_flag = factor(A1_expr_outlier_flag, levels = c("low", "neither", "high")))

```

```{r}

d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers <- d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_unfiltered %>%
  group_by(target, compound_id) %>%
  ## get rid of drug/targets that don't have any "low" cell lines
  filter(any(A2_expr_outlier_flag == "low")) %>%
  ungroup() 

d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_grp_med_diff <- d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers %>%
  group_by(target, compound_id, A2_expr_outlier_flag) %>%
  ## calculate median dependency score for each outlier group
  summarize(grp_med_dependency = median(dependency)) %>%
  pivot_wider(names_from = A2_expr_outlier_flag, values_from = grp_med_dependency) %>%
  ## calculate difference between low and neither groups
  mutate(grp_med_diff = low - neither) %>%
  dplyr::select(target, compound_id, grp_med_diff) 

d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers <- d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers %>%
  left_join(d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_grp_med_diff, by = c("target", "compound_id"))

## low outliers and drug sensitivity
d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_wrst_pvals <- d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers %>%
  filter(A2_expr_outlier_flag != "high") %>%
  group_by(target, compound_id) %>%
  summarize(p_val = wilcox.test(dependency ~ A2_expr_outlier_flag)$p.value)

## adjust for multiple testing overall
d.stats <- BH_adjust(d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_wrst_pvals)

d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_wrst <- d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers %>%
  left_join(d.stats, by = c("target", "compound_id")) 

## filter for hits where low-expressing cell lines are more sensitive to the drug
## (low group has lower median than neither group)
d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_wrst_sens <- d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_wrst %>%
  filter(grp_med_diff < 0)

## filter for hits where low-expressing ell lines are more resistant to the drug
## (low group has higher median than neither group)
d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_wrst_resist <- d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_wrst %>%
  filter(grp_med_diff > 0)

summarize_stats(d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_wrst_sens)
summarize_stats(d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_wrst_resist)

```

##### Plot

```{r, message=FALSE, fig.height=9}

plot_list <- d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_wrst_sens %>%
  unite("target_compound_id", c("target", "compound_name"), sep = "\n", remove = FALSE) %>%
  distinct(target_compound_id) %>%
  pull(target_compound_id)

make_outlier_plot(d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_wrst_sens,
                  plot_list[1:4], "low", A2_expr_outlier_flag, A2_log_tpm)

make_outlier_plot(d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_wrst_sens,
                  plot_list[5:8], "low", A2_expr_outlier_flag, A2_log_tpm)

```

```{r, message=FALSE, fig.height=7}

make_lineage_plot(d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_wrst_sens,
                  plot_list, A2_log_tpm, A2_expr_outlier_flag)

```

```{r}

write_rds(d.DeKegel_top5_pairs_drug_sens_expr_A2_lm_pos_top_outliers_wrst_sens, 
          file.path(out_dir, "d.top_outlier_pairs"))

```
